.TH SAPLING 1 "2020-12-10" "0.1.0-rc.1" "sapling"

.SH NAME
sapling \- general\-purpose compiler


.SH SYNOPSIS
.B sapling
[\fB\-f\fIoption\fR...] spec_file


.SH DESCRIPTION
.B sapling
is in its initial development. Currently it only checks whether a specification
file is syntactically correct.


.SH OPTIONS
Lexer diagnostics do not invoke the parser, making these options are mutually
exclusive with both parser and output diagnostics options, since these last
depend on a successful parse. Many options take an optional file parameter
where to redirect the output. If it is not specified the output is redirected
to standard output.

.SS \fI Lexer Diagnostics
.B \-fprint\-lexer\-output\-only[=\fIfile\fR]

.SS \fI Parser Diagnostics
.B \-flog\-state\-stack \-flog\-production\-stack
.B \-fdump\-parse\-tree[=\fIfile\fR]

.SS \fI Output Diagnostics
.B \-fprint\-terminals
.B \-fprint\-nonterminals
.B \-fdump\-lexer\-automaton[=\fIfile\fR]
