#! /bin/sh

terminals=$(./sapling-backup ../spec/meta -fprint-terminals 2> /dev/null)

echo "#include <libsapling/cc/terminal.h>"
echo "#include \"autogen_terminals.h\""
echo "#include \"mangen_user_data.h\""
echo ""
echo "void lexer_action(terminal_t terminal, void *user_ptr)"
echo "{"
echo "    struct user *user = user_ptr;"
echo "    switch (terminal__id(terminal)) {"
for t in $terminals; do
    echo "    case $t:"
    echo "        break;"
done
echo "    }"
echo "}"
